export const DEVICE_PLATFORMS = ['ios', 'android', 'web'] as const;
export type DevicePlatform = (typeof DEVICE_PLATFORMS)[number];

/**
 * One app install of a user. A user can be signed in on several devices; each one gets
 * pushes through its own FCM token.
 */
export interface Device {
  id: string;
  userId: string;
  /** Generated by the app once per install – the same install always sends the same id. */
  deviceId: string;
  /** FCM registration token (null until the app has one, e.g. push permission denied). */
  token: string | null;
  platform: DevicePlatform;
  /** e.g. "Pixel 8" / "iPhone". */
  deviceName: string | null;
  osVersion: string | null;
  appVersion: string | null;
  /** The last time the app registered (every app start and sign-in). */
  lastActiveAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

/** What the app sends on sign-in, on app start and when its FCM token changes. */
export interface DeviceInput {
  deviceId: string;
  token?: string | null;
  platform: DevicePlatform;
  deviceName?: string | null;
  osVersion?: string | null;
  appVersion?: string | null;
}

export interface DeviceView {
  deviceId: string;
  platform: DevicePlatform;
  deviceName: string | null;
  osVersion: string | null;
  appVersion: string | null;
  /** Push is possible on this device. */
  pushEnabled: boolean;
  lastActiveAt: string;
  createdAt: string;
}

export function toDeviceView(d: Device): DeviceView {
  return {
    deviceId: d.deviceId,
    platform: d.platform,
    deviceName: d.deviceName,
    osVersion: d.osVersion,
    appVersion: d.appVersion,
    pushEnabled: d.token !== null,
    lastActiveAt: d.lastActiveAt.toISOString(),
    createdAt: d.createdAt.toISOString(),
  };
}
