/** Where the app runs – a database enum (devices.device_type). */
export enum DeviceType {
  IOS = 'IOS',
  ANDROID = 'ANDROID',
  WEB = 'WEB',
}

/**
 * One app install of a user. A user can be signed in on several devices; each one gets
 * pushes through its own FCM token.
 */
export interface Device {
  id: string;
  userId: string;
  /** Generated by the app once per install – the same install always sends the same id. */
  deviceId: string;
  /** FCM registration token (null until the app has one, e.g. push permission denied). */
  fcmToken: string | null;
  /** iOS VoIP push token for incoming calls (PushKit) – null on Android or when not provided. */
  voipToken: string | null;
  deviceType: DeviceType;
  /** e.g. "Google Pixel 8" / "iPhone". */
  deviceModel: string | null;
  osVersion: string | null;
  appVersion: string | null;
  /** The last sign-in / token refresh from this install. */
  lastActiveAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * The `device` of the login / register / OTP / social / refresh payloads – the backend creates
 * or updates the install while signing the user in (there is no separate device request).
 */
export interface DeviceInput {
  deviceId: string;
  deviceType: DeviceType;
  deviceModel?: string | null;
  osVersion?: string | null;
  appVersion?: string | null;
  fcmToken?: string | null;
  voipToken?: string | null;
}

export interface DeviceView {
  deviceId: string;
  deviceType: DeviceType;
  deviceModel: string | null;
  osVersion: string | null;
  appVersion: string | null;
  /** Push is possible on this device. */
  pushEnabled: boolean;
  /** VoIP push is enabled (iOS CallKit wake). */
  voipEnabled: boolean;
  lastActiveAt: string;
  createdAt: string;
}

export function toDeviceView(d: Device): DeviceView {
  return {
    deviceId: d.deviceId,
    deviceType: d.deviceType,
    deviceModel: d.deviceModel,
    osVersion: d.osVersion,
    appVersion: d.appVersion,
    pushEnabled: d.fcmToken !== null,
    voipEnabled: d.voipToken !== null,
    lastActiveAt: d.lastActiveAt.toISOString(),
    createdAt: d.createdAt.toISOString(),
  };
}

/**
 * What sign-in needs from the devices feature: AuthService saves the payload's device after
 * login / register / OTP / social sign-in / refresh and removes it on logout. DevicesService
 * implements it; the microservices identity service publishes the changes instead.
 */
export interface DeviceRegistry {
  save(userId: string, device: DeviceInput): Promise<void>;
  /** One install (logout). Unknown devices are ignored. */
  remove(userId: string, deviceId: string): Promise<void>;
  /** Every install of the user ("sign out everywhere"). */
  removeAll(userId: string): Promise<void>;
}
