import { IsIn, IsOptional, IsString, MaxLength, MinLength } from 'class-validator';
import { DEVICE_PLATFORMS, type DevicePlatform } from '{{IMPORT:domain.device}}';

export class RegisterDeviceDto {
  /** Generated by the app once per install. */
  @IsString()
  @MinLength(8)
  @MaxLength(128)
  deviceId: string;

  /** FCM registration token (null when the app has none). */
  @IsOptional()
  @IsString()
  @MinLength(10)
  @MaxLength(512)
  token?: string | null;

  @IsIn(DEVICE_PLATFORMS)
  platform: DevicePlatform;

  /** e.g. "Pixel 8". */
  @IsOptional()
  @IsString()
  @MaxLength(120)
  deviceName?: string | null;

  @IsOptional()
  @IsString()
  @MaxLength(32)
  osVersion?: string | null;

  @IsOptional()
  @IsString()
  @MaxLength(32)
  appVersion?: string | null;
}

// ── responses (documentation) ────────────────────────────────────────────────

export class DeviceDto {
  deviceId: string;
  platform: DevicePlatform;
  deviceName: string | null;
  osVersion: string | null;
  appVersion: string | null;
  pushEnabled: boolean;
  lastActiveAt: string;
  createdAt: string;
}
