import type { ImageSourcePropType } from 'react-native';

/** A country for the phone number picker: ISO code, dial code and flag image. */
export interface Country {
  name: string;
  /** ISO 3166-1 alpha-2, e.g. "IN". */
  code: string;
  /** e.g. "+91". */
  dialCode: string;
  flag: ImageSourcePropType;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: 'AF', dialCode: '+93', flag: require('./af.png') },
  { name: "Aland Islands", code: 'AX', dialCode: '+358', flag: require('./ax.png') },
  { name: "Albania", code: 'AL', dialCode: '+355', flag: require('./al.png') },
  { name: "Algeria", code: 'DZ', dialCode: '+213', flag: require('./dz.png') },
  { name: "American Samoa", code: 'AS', dialCode: '+1684', flag: require('./as.png') },
  { name: "Andorra", code: 'AD', dialCode: '+376', flag: require('./ad.png') },
  { name: "Angola", code: 'AO', dialCode: '+244', flag: require('./ao.png') },
  { name: "Anguilla", code: 'AI', dialCode: '+1264', flag: require('./ai.png') },
  { name: "Antarctica", code: 'AQ', dialCode: '+672', flag: require('./aq.png') },
  { name: "Antigua and Barbuda", code: 'AG', dialCode: '+1268', flag: require('./ag.png') },
  { name: "Argentina", code: 'AR', dialCode: '+54', flag: require('./ar.png') },
  { name: "Armenia", code: 'AM', dialCode: '+374', flag: require('./am.png') },
  { name: "Aruba", code: 'AW', dialCode: '+297', flag: require('./aw.png') },
  { name: "Australia", code: 'AU', dialCode: '+61', flag: require('./au.png') },
  { name: "Austria", code: 'AT', dialCode: '+43', flag: require('./at.png') },
  { name: "Azerbaijan", code: 'AZ', dialCode: '+994', flag: require('./az.png') },
  { name: "Bahamas", code: 'BS', dialCode: '+1242', flag: require('./bs.png') },
  { name: "Bahrain", code: 'BH', dialCode: '+973', flag: require('./bh.png') },
  { name: "Bangladesh", code: 'BD', dialCode: '+880', flag: require('./bd.png') },
  { name: "Barbados", code: 'BB', dialCode: '+1246', flag: require('./bb.png') },
  { name: "Belarus", code: 'BY', dialCode: '+375', flag: require('./by.png') },
  { name: "Belgium", code: 'BE', dialCode: '+32', flag: require('./be.png') },
  { name: "Belize", code: 'BZ', dialCode: '+501', flag: require('./bz.png') },
  { name: "Benin", code: 'BJ', dialCode: '+229', flag: require('./bj.png') },
  { name: "Bermuda", code: 'BM', dialCode: '+1441', flag: require('./bm.png') },
  { name: "Bhutan", code: 'BT', dialCode: '+975', flag: require('./bt.png') },
  { name: "Bolivia, Plurinational State of", code: 'BO', dialCode: '+591', flag: require('./bo.png') },
  { name: "Bosnia and Herzegovina", code: 'BA', dialCode: '+387', flag: require('./ba.png') },
  { name: "Botswana", code: 'BW', dialCode: '+267', flag: require('./bw.png') },
  { name: "Brazil", code: 'BR', dialCode: '+55', flag: require('./br.png') },
  { name: "British Indian Ocean Territory", code: 'IO', dialCode: '+246', flag: require('./io.png') },
  { name: "Brunei Darussalam", code: 'BN', dialCode: '+673', flag: require('./bn.png') },
  { name: "Bulgaria", code: 'BG', dialCode: '+359', flag: require('./bg.png') },
  { name: "Burkina Faso", code: 'BF', dialCode: '+226', flag: require('./bf.png') },
  { name: "Burundi", code: 'BI', dialCode: '+257', flag: require('./bi.png') },
  { name: "Cambodia", code: 'KH', dialCode: '+855', flag: require('./kh.png') },
  { name: "Cameroon", code: 'CM', dialCode: '+237', flag: require('./cm.png') },
  { name: "Canada", code: 'CA', dialCode: '+1', flag: require('./ca.png') },
  { name: "Cape Verde", code: 'CV', dialCode: '+238', flag: require('./cv.png') },
  { name: "Cayman Islands", code: 'KY', dialCode: '+345', flag: require('./ky.png') },
  { name: "Central African Republic", code: 'CF', dialCode: '+236', flag: require('./cf.png') },
  { name: "Chad", code: 'TD', dialCode: '+235', flag: require('./td.png') },
  { name: "Chile", code: 'CL', dialCode: '+56', flag: require('./cl.png') },
  { name: "China", code: 'CN', dialCode: '+86', flag: require('./cn.png') },
  { name: "Christmas Island", code: 'CX', dialCode: '+61', flag: require('./cx.png') },
  { name: "Cocos (Keeling) Islands", code: 'CC', dialCode: '+61', flag: require('./cc.png') },
  { name: "Colombia", code: 'CO', dialCode: '+57', flag: require('./co.png') },
  { name: "Comoros", code: 'KM', dialCode: '+269', flag: require('./km.png') },
  { name: "Congo", code: 'CG', dialCode: '+242', flag: require('./cg.png') },
  { name: "Congo, The Democratic Republic of the Congo", code: 'CD', dialCode: '+243', flag: require('./cd.png') },
  { name: "Cook Islands", code: 'CK', dialCode: '+682', flag: require('./ck.png') },
  { name: "Costa Rica", code: 'CR', dialCode: '+506', flag: require('./cr.png') },
  { name: "Cote d'Ivoire", code: 'CI', dialCode: '+225', flag: require('./ci.png') },
  { name: "Croatia", code: 'HR', dialCode: '+385', flag: require('./hr.png') },
  { name: "Cuba", code: 'CU', dialCode: '+53', flag: require('./cu.png') },
  { name: "Cyprus", code: 'CY', dialCode: '+357', flag: require('./cy.png') },
  { name: "Czech Republic", code: 'CZ', dialCode: '+420', flag: require('./cz.png') },
  { name: "Denmark", code: 'DK', dialCode: '+45', flag: require('./dk.png') },
  { name: "Djibouti", code: 'DJ', dialCode: '+253', flag: require('./dj.png') },
  { name: "Dominica", code: 'DM', dialCode: '+1767', flag: require('./dm.png') },
  { name: "Dominican Republic", code: 'DO', dialCode: '+1849', flag: require('./do.png') },
  { name: "Ecuador", code: 'EC', dialCode: '+593', flag: require('./ec.png') },
  { name: "Egypt", code: 'EG', dialCode: '+20', flag: require('./eg.png') },
  { name: "El Salvador", code: 'SV', dialCode: '+503', flag: require('./sv.png') },
  { name: "Equatorial Guinea", code: 'GQ', dialCode: '+240', flag: require('./gq.png') },
  { name: "Eritrea", code: 'ER', dialCode: '+291', flag: require('./er.png') },
  { name: "Estonia", code: 'EE', dialCode: '+372', flag: require('./ee.png') },
  { name: "Ethiopia", code: 'ET', dialCode: '+251', flag: require('./et.png') },
  { name: "Falkland Islands (Malvinas)", code: 'FK', dialCode: '+500', flag: require('./fk.png') },
  { name: "Faroe Islands", code: 'FO', dialCode: '+298', flag: require('./fo.png') },
  { name: "Fiji", code: 'FJ', dialCode: '+679', flag: require('./fj.png') },
  { name: "Finland", code: 'FI', dialCode: '+358', flag: require('./fi.png') },
  { name: "France", code: 'FR', dialCode: '+33', flag: require('./fr.png') },
  { name: "French Guiana", code: 'GF', dialCode: '+594', flag: require('./gf.png') },
  { name: "French Polynesia", code: 'PF', dialCode: '+689', flag: require('./pf.png') },
  { name: "Gabon", code: 'GA', dialCode: '+241', flag: require('./ga.png') },
  { name: "Gambia", code: 'GM', dialCode: '+220', flag: require('./gm.png') },
  { name: "Georgia", code: 'GE', dialCode: '+995', flag: require('./ge.png') },
  { name: "Germany", code: 'DE', dialCode: '+49', flag: require('./de.png') },
  { name: "Ghana", code: 'GH', dialCode: '+233', flag: require('./gh.png') },
  { name: "Gibraltar", code: 'GI', dialCode: '+350', flag: require('./gi.png') },
  { name: "Greece", code: 'GR', dialCode: '+30', flag: require('./gr.png') },
  { name: "Greenland", code: 'GL', dialCode: '+299', flag: require('./gl.png') },
  { name: "Grenada", code: 'GD', dialCode: '+1473', flag: require('./gd.png') },
  { name: "Guadeloupe", code: 'GP', dialCode: '+590', flag: require('./gp.png') },
  { name: "Guam", code: 'GU', dialCode: '+1671', flag: require('./gu.png') },
  { name: "Guatemala", code: 'GT', dialCode: '+502', flag: require('./gt.png') },
  { name: "Guernsey", code: 'GG', dialCode: '+44', flag: require('./gg.png') },
  { name: "Guinea", code: 'GN', dialCode: '+224', flag: require('./gn.png') },
  { name: "Guinea-Bissau", code: 'GW', dialCode: '+245', flag: require('./gw.png') },
  { name: "Guyana", code: 'GY', dialCode: '+595', flag: require('./gy.png') },
  { name: "Haiti", code: 'HT', dialCode: '+509', flag: require('./ht.png') },
  { name: "Holy See (Vatican City State)", code: 'VA', dialCode: '+379', flag: require('./va.png') },
  { name: "Honduras", code: 'HN', dialCode: '+504', flag: require('./hn.png') },
  { name: "Hong Kong", code: 'HK', dialCode: '+852', flag: require('./hk.png') },
  { name: "Hungary", code: 'HU', dialCode: '+36', flag: require('./hu.png') },
  { name: "Iceland", code: 'IS', dialCode: '+354', flag: require('./is.png') },
  { name: "India", code: 'IN', dialCode: '+91', flag: require('./in.png') },
  { name: "Indonesia", code: 'ID', dialCode: '+62', flag: require('./id.png') },
  { name: "Iran, Islamic Republic of Persian Gulf", code: 'IR', dialCode: '+98', flag: require('./ir.png') },
  { name: "Iraq", code: 'IQ', dialCode: '+964', flag: require('./iq.png') },
  { name: "Ireland", code: 'IE', dialCode: '+353', flag: require('./ie.png') },
  { name: "Isle of Man", code: 'IM', dialCode: '+44', flag: require('./im.png') },
  { name: "Israel", code: 'IL', dialCode: '+972', flag: require('./il.png') },
  { name: "Italy", code: 'IT', dialCode: '+39', flag: require('./it.png') },
  { name: "Jamaica", code: 'JM', dialCode: '+1876', flag: require('./jm.png') },
  { name: "Japan", code: 'JP', dialCode: '+81', flag: require('./jp.png') },
  { name: "Jersey", code: 'JE', dialCode: '+44', flag: require('./je.png') },
  { name: "Jordan", code: 'JO', dialCode: '+962', flag: require('./jo.png') },
  { name: "Kazakhstan", code: 'KZ', dialCode: '+77', flag: require('./kz.png') },
  { name: "Kenya", code: 'KE', dialCode: '+254', flag: require('./ke.png') },
  { name: "Kiribati", code: 'KI', dialCode: '+686', flag: require('./ki.png') },
  { name: "Korea, Democratic People's Republic of Korea", code: 'KP', dialCode: '+850', flag: require('./kp.png') },
  { name: "Korea, Republic of South Korea", code: 'KR', dialCode: '+82', flag: require('./kr.png') },
  { name: "Kuwait", code: 'KW', dialCode: '+965', flag: require('./kw.png') },
  { name: "Kyrgyzstan", code: 'KG', dialCode: '+996', flag: require('./kg.png') },
  { name: "Laos", code: 'LA', dialCode: '+856', flag: require('./la.png') },
  { name: "Latvia", code: 'LV', dialCode: '+371', flag: require('./lv.png') },
  { name: "Lebanon", code: 'LB', dialCode: '+961', flag: require('./lb.png') },
  { name: "Lesotho", code: 'LS', dialCode: '+266', flag: require('./ls.png') },
  { name: "Liberia", code: 'LR', dialCode: '+231', flag: require('./lr.png') },
  { name: "Libyan Arab Jamahiriya", code: 'LY', dialCode: '+218', flag: require('./ly.png') },
  { name: "Liechtenstein", code: 'LI', dialCode: '+423', flag: require('./li.png') },
  { name: "Lithuania", code: 'LT', dialCode: '+370', flag: require('./lt.png') },
  { name: "Luxembourg", code: 'LU', dialCode: '+352', flag: require('./lu.png') },
  { name: "Macao", code: 'MO', dialCode: '+853', flag: require('./mo.png') },
  { name: "Macedonia", code: 'MK', dialCode: '+389', flag: require('./mk.png') },
  { name: "Madagascar", code: 'MG', dialCode: '+261', flag: require('./mg.png') },
  { name: "Malawi", code: 'MW', dialCode: '+265', flag: require('./mw.png') },
  { name: "Malaysia", code: 'MY', dialCode: '+60', flag: require('./my.png') },
  { name: "Maldives", code: 'MV', dialCode: '+960', flag: require('./mv.png') },
  { name: "Mali", code: 'ML', dialCode: '+223', flag: require('./ml.png') },
  { name: "Malta", code: 'MT', dialCode: '+356', flag: require('./mt.png') },
  { name: "Marshall Islands", code: 'MH', dialCode: '+692', flag: require('./mh.png') },
  { name: "Martinique", code: 'MQ', dialCode: '+596', flag: require('./mq.png') },
  { name: "Mauritania", code: 'MR', dialCode: '+222', flag: require('./mr.png') },
  { name: "Mauritius", code: 'MU', dialCode: '+230', flag: require('./mu.png') },
  { name: "Mayotte", code: 'YT', dialCode: '+262', flag: require('./yt.png') },
  { name: "Mexico", code: 'MX', dialCode: '+52', flag: require('./mx.png') },
  { name: "Micronesia, Federated States of Micronesia", code: 'FM', dialCode: '+691', flag: require('./fm.png') },
  { name: "Moldova", code: 'MD', dialCode: '+373', flag: require('./md.png') },
  { name: "Monaco", code: 'MC', dialCode: '+377', flag: require('./mc.png') },
  { name: "Mongolia", code: 'MN', dialCode: '+976', flag: require('./mn.png') },
  { name: "Montenegro", code: 'ME', dialCode: '+382', flag: require('./me.png') },
  { name: "Montserrat", code: 'MS', dialCode: '+1664', flag: require('./ms.png') },
  { name: "Morocco", code: 'MA', dialCode: '+212', flag: require('./ma.png') },
  { name: "Mozambique", code: 'MZ', dialCode: '+258', flag: require('./mz.png') },
  { name: "Myanmar", code: 'MM', dialCode: '+95', flag: require('./mm.png') },
  { name: "Namibia", code: 'NA', dialCode: '+264', flag: require('./na.png') },
  { name: "Nauru", code: 'NR', dialCode: '+674', flag: require('./nr.png') },
  { name: "Nepal", code: 'NP', dialCode: '+977', flag: require('./np.png') },
  { name: "Netherlands", code: 'NL', dialCode: '+31', flag: require('./nl.png') },
  { name: "New Caledonia", code: 'NC', dialCode: '+687', flag: require('./nc.png') },
  { name: "New Zealand", code: 'NZ', dialCode: '+64', flag: require('./nz.png') },
  { name: "Nicaragua", code: 'NI', dialCode: '+505', flag: require('./ni.png') },
  { name: "Niger", code: 'NE', dialCode: '+227', flag: require('./ne.png') },
  { name: "Nigeria", code: 'NG', dialCode: '+234', flag: require('./ng.png') },
  { name: "Niue", code: 'NU', dialCode: '+683', flag: require('./nu.png') },
  { name: "Norfolk Island", code: 'NF', dialCode: '+672', flag: require('./nf.png') },
  { name: "Northern Mariana Islands", code: 'MP', dialCode: '+1670', flag: require('./mp.png') },
  { name: "Norway", code: 'NO', dialCode: '+47', flag: require('./no.png') },
  { name: "Oman", code: 'OM', dialCode: '+968', flag: require('./om.png') },
  { name: "Pakistan", code: 'PK', dialCode: '+92', flag: require('./pk.png') },
  { name: "Palau", code: 'PW', dialCode: '+680', flag: require('./pw.png') },
  { name: "Palestinian Territory, Occupied", code: 'PS', dialCode: '+970', flag: require('./ps.png') },
  { name: "Panama", code: 'PA', dialCode: '+507', flag: require('./pa.png') },
  { name: "Papua New Guinea", code: 'PG', dialCode: '+675', flag: require('./pg.png') },
  { name: "Paraguay", code: 'PY', dialCode: '+595', flag: require('./py.png') },
  { name: "Peru", code: 'PE', dialCode: '+51', flag: require('./pe.png') },
  { name: "Philippines", code: 'PH', dialCode: '+63', flag: require('./ph.png') },
  { name: "Pitcairn", code: 'PN', dialCode: '+872', flag: require('./pn.png') },
  { name: "Poland", code: 'PL', dialCode: '+48', flag: require('./pl.png') },
  { name: "Portugal", code: 'PT', dialCode: '+351', flag: require('./pt.png') },
  { name: "Puerto Rico", code: 'PR', dialCode: '+1939', flag: require('./pr.png') },
  { name: "Qatar", code: 'QA', dialCode: '+974', flag: require('./qa.png') },
  { name: "Reunion", code: 'RE', dialCode: '+262', flag: require('./re.png') },
  { name: "Romania", code: 'RO', dialCode: '+40', flag: require('./ro.png') },
  { name: "Russia", code: 'RU', dialCode: '+7', flag: require('./ru.png') },
  { name: "Rwanda", code: 'RW', dialCode: '+250', flag: require('./rw.png') },
  { name: "Saint Barthelemy", code: 'BL', dialCode: '+590', flag: require('./bl.png') },
  { name: "Saint Helena, Ascension and Tristan Da Cunha", code: 'SH', dialCode: '+290', flag: require('./sh.png') },
  { name: "Saint Kitts and Nevis", code: 'KN', dialCode: '+1869', flag: require('./kn.png') },
  { name: "Saint Lucia", code: 'LC', dialCode: '+1758', flag: require('./lc.png') },
  { name: "Saint Martin", code: 'MF', dialCode: '+590', flag: require('./mf.png') },
  { name: "Saint Pierre and Miquelon", code: 'PM', dialCode: '+508', flag: require('./pm.png') },
  { name: "Saint Vincent and the Grenadines", code: 'VC', dialCode: '+1784', flag: require('./vc.png') },
  { name: "Samoa", code: 'WS', dialCode: '+685', flag: require('./ws.png') },
  { name: "San Marino", code: 'SM', dialCode: '+378', flag: require('./sm.png') },
  { name: "Sao Tome and Principe", code: 'ST', dialCode: '+239', flag: require('./st.png') },
  { name: "Saudi Arabia", code: 'SA', dialCode: '+966', flag: require('./sa.png') },
  { name: "Senegal", code: 'SN', dialCode: '+221', flag: require('./sn.png') },
  { name: "Serbia", code: 'RS', dialCode: '+381', flag: require('./rs.png') },
  { name: "Seychelles", code: 'SC', dialCode: '+248', flag: require('./sc.png') },
  { name: "Sierra Leone", code: 'SL', dialCode: '+232', flag: require('./sl.png') },
  { name: "Singapore", code: 'SG', dialCode: '+65', flag: require('./sg.png') },
  { name: "Slovakia", code: 'SK', dialCode: '+421', flag: require('./sk.png') },
  { name: "Slovenia", code: 'SI', dialCode: '+386', flag: require('./si.png') },
  { name: "Solomon Islands", code: 'SB', dialCode: '+677', flag: require('./sb.png') },
  { name: "Somalia", code: 'SO', dialCode: '+252', flag: require('./so.png') },
  { name: "South Africa", code: 'ZA', dialCode: '+27', flag: require('./za.png') },
  { name: "South Georgia and the South Sandwich Islands", code: 'GS', dialCode: '+500', flag: require('./gs.png') },
  { name: "South Sudan", code: 'SS', dialCode: '+211', flag: require('./ss.png') },
  { name: "Spain", code: 'ES', dialCode: '+34', flag: require('./es.png') },
  { name: "Sri Lanka", code: 'LK', dialCode: '+94', flag: require('./lk.png') },
  { name: "Sudan", code: 'SD', dialCode: '+249', flag: require('./sd.png') },
  { name: "Suriname", code: 'SR', dialCode: '+597', flag: require('./sr.png') },
  { name: "Svalbard and Jan Mayen", code: 'SJ', dialCode: '+47', flag: require('./sj.png') },
  { name: "Swaziland", code: 'SZ', dialCode: '+268', flag: require('./sz.png') },
  { name: "Sweden", code: 'SE', dialCode: '+46', flag: require('./se.png') },
  { name: "Switzerland", code: 'CH', dialCode: '+41', flag: require('./ch.png') },
  { name: "Syrian Arab Republic", code: 'SY', dialCode: '+963', flag: require('./sy.png') },
  { name: "Taiwan", code: 'TW', dialCode: '+886', flag: require('./tw.png') },
  { name: "Tajikistan", code: 'TJ', dialCode: '+992', flag: require('./tj.png') },
  { name: "Tanzania, United Republic of Tanzania", code: 'TZ', dialCode: '+255', flag: require('./tz.png') },
  { name: "Thailand", code: 'TH', dialCode: '+66', flag: require('./th.png') },
  { name: "Timor-Leste", code: 'TL', dialCode: '+670', flag: require('./tl.png') },
  { name: "Togo", code: 'TG', dialCode: '+228', flag: require('./tg.png') },
  { name: "Tokelau", code: 'TK', dialCode: '+690', flag: require('./tk.png') },
  { name: "Tonga", code: 'TO', dialCode: '+676', flag: require('./to.png') },
  { name: "Trinidad and Tobago", code: 'TT', dialCode: '+1868', flag: require('./tt.png') },
  { name: "Tunisia", code: 'TN', dialCode: '+216', flag: require('./tn.png') },
  { name: "Turkey", code: 'TR', dialCode: '+90', flag: require('./tr.png') },
  { name: "Turkmenistan", code: 'TM', dialCode: '+993', flag: require('./tm.png') },
  { name: "Turks and Caicos Islands", code: 'TC', dialCode: '+1649', flag: require('./tc.png') },
  { name: "Tuvalu", code: 'TV', dialCode: '+688', flag: require('./tv.png') },
  { name: "Uganda", code: 'UG', dialCode: '+256', flag: require('./ug.png') },
  { name: "Ukraine", code: 'UA', dialCode: '+380', flag: require('./ua.png') },
  { name: "United Arab Emirates", code: 'AE', dialCode: '+971', flag: require('./ae.png') },
  { name: "United Kingdom", code: 'GB', dialCode: '+44', flag: require('./gb.png') },
  { name: "United States", code: 'US', dialCode: '+1', flag: require('./us.png') },
  { name: "Uruguay", code: 'UY', dialCode: '+598', flag: require('./uy.png') },
  { name: "Uzbekistan", code: 'UZ', dialCode: '+998', flag: require('./uz.png') },
  { name: "Vanuatu", code: 'VU', dialCode: '+678', flag: require('./vu.png') },
  { name: "Venezuela, Bolivarian Republic of Venezuela", code: 'VE', dialCode: '+58', flag: require('./ve.png') },
  { name: "Vietnam", code: 'VN', dialCode: '+84', flag: require('./vn.png') },
  { name: "Virgin Islands, British", code: 'VG', dialCode: '+1284', flag: require('./vg.png') },
  { name: "Virgin Islands, U.S.", code: 'VI', dialCode: '+1340', flag: require('./vi.png') },
  { name: "Wallis and Futuna", code: 'WF', dialCode: '+681', flag: require('./wf.png') },
  { name: "Yemen", code: 'YE', dialCode: '+967', flag: require('./ye.png') },
  { name: "Zambia", code: 'ZM', dialCode: '+260', flag: require('./zm.png') },
  { name: "Zimbabwe", code: 'ZW', dialCode: '+263', flag: require('./zw.png') },
];

export function findCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(country => country.code === code.toUpperCase());
}

/** The longest dial code that matches wins ("+1684" American Samoa before "+1"). */
export function findCountryByDialCode(dialCode: string): Country | undefined {
  const normalized = `+${dialCode.replace(/\D/g, '')}`;
  return COUNTRIES.filter(country => country.dialCode === normalized).sort((a, b) => a.name.localeCompare(b.name))[0];
}

/** The device's region (e.g. en-IN → India), falling back to the United States. */
export function defaultCountry(): Country {
  const locale = Intl.DateTimeFormat().resolvedOptions().locale;
  const region = /[-_]([A-Z]{2})\b/.exec(locale)?.[1];
  return (region && findCountryByCode(region)) || findCountryByCode('US') || COUNTRIES[0]!;
}
