import path from 'node:path';
import fs from 'fs-extra';
import plist from 'plist';
import xcode from 'xcode';
import { applyPatches } from '../../utils/nativePatch.js';

function iosPaths(projectDir: string, appName: string) {
  const ios = path.join(projectDir, 'ios');
  return {
    ios,
    podfile: path.join(ios, 'Podfile'),
    appDelegate: path.join(ios, appName, 'AppDelegate.swift'),
    infoPlist: path.join(ios, appName, 'Info.plist'),
  };
}

async function edit(file: string, transform: (source: string) => string): Promise<void> {
  if (!(await fs.pathExists(file))) return;
  const source = await fs.readFile(file, 'utf8');
  const next = transform(source);
  if (next !== source) await fs.writeFile(file, next, 'utf8');
}

/**
 * Info.plist:
 * - NSMicrophoneUsageDescription (audio + video calls)
 * - NSCameraUsageDescription (video calls)
 * - UIBackgroundModes: voip (required for PushKit VoIP wake) + audio
 */
export async function configureIosCalling(projectDir: string, appName: string, displayName: string, hasVideo: boolean): Promise<void> {
  const { infoPlist } = iosPaths(projectDir, appName);
  if (!(await fs.pathExists(infoPlist))) return;

  const data = plist.parse(await fs.readFile(infoPlist, 'utf8')) as Record<string, plist.PlistValue>;

  data.NSMicrophoneUsageDescription ??= `${displayName} uses the microphone for calls.`;
  if (hasVideo) {
    data.NSCameraUsageDescription ??= `${displayName} uses the camera for video calls.`;
  }

  // Background modes: 'voip' wakes the app for PushKit; 'audio' keeps Agora running.
  const modes = new Set(Array.isArray(data.UIBackgroundModes) ? (data.UIBackgroundModes as string[]) : []);
  modes.add('voip');
  modes.add('audio');
  data.UIBackgroundModes = [...modes];

  await fs.writeFile(infoPlist, plist.build(data, { indent: '\t', pretty: true }) + '\n', 'utf8');
}

/**
 * AppDelegate.swift: Register for VoIP notifications with PushKit.
 * react-native-voip-push-notification handles the actual registration;
 * we only need to ensure the background mode is configured.
 * CallKit (via react-native-callkeep) is auto-configured by the library.
 */
export async function configureIosCallingAppDelegate(projectDir: string, appName: string): Promise<void> {
  const { appDelegate } = iosPaths(projectDir, appName);
  await edit(appDelegate, source =>
    applyPatches(
      source,
      [
        {
          id: 'voip-import',
          anchor: /^import UIKit$/m,
          position: 'after',
          comment: '//',
          content: [
            '// react-native-voip-push-notification (PushKit – wakes app for incoming calls)',
            'import PushKit',
          ].join('\n'),
        },
      ],
      'AppDelegate.swift',
    ),
  );
}

/** File name of the native PushKit handler written next to AppDelegate.swift. */
export const VOIP_PUSH_HANDLER_FILE = 'VoipPushHandler.m';

/**
 * Native PushKit handler (Objective-C, starts itself – AppDelegate.swift is not touched).
 *
 * iOS 13+ terminates an app that receives a VoIP push and does not report a call to CallKit right away,
 * and stops delivering VoIP pushes to it. JavaScript may not even be running yet (app killed), so the call
 * is reported here, natively, with the `uuid` from the payload (the backend sends the same uuid over the
 * socket and FCM, so the JS side reports the same CallKit call, never a second one). The payload is then
 * handed to react-native-voip-push-notification so JS gets it ('notification' / 'didLoadWithEvents').
 */
export function getVoipPushHandlerSource(): string {
  return `// Generated by rn-architecture-generator – PushKit (VoIP push) → CallKit, before JavaScript runs.
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <PushKit/PushKit.h>
#import <RNCallKeep/RNCallKeep.h>
#import <RNVoipPushNotification/RNVoipPushNotificationManager.h>

@interface VoipPushHandler : NSObject <PKPushRegistryDelegate>
@property (nonatomic, strong) PKPushRegistry *registry;
@end

@implementation VoipPushHandler

static VoipPushHandler *sharedHandler;

// Runs when the app binary loads: register for VoIP pushes as soon as the app has launched.
+ (void)load
{
  [[NSNotificationCenter defaultCenter] addObserverForName:UIApplicationDidFinishLaunchingNotification
                                                    object:nil
                                                     queue:[NSOperationQueue mainQueue]
                                                usingBlock:^(NSNotification *note) {
    if (sharedHandler != nil) return;
    sharedHandler = [VoipPushHandler new];
    sharedHandler.registry = [[PKPushRegistry alloc] initWithQueue:dispatch_get_main_queue()];
    sharedHandler.registry.delegate = sharedHandler;
    sharedHandler.registry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];
  }];
}

- (void)pushRegistry:(PKPushRegistry *)registry didUpdatePushCredentials:(PKPushCredentials *)credentials forType:(PKPushType)type
{
  // The JS side receives the token through react-native-voip-push-notification ('register').
  [RNVoipPushNotificationManager didUpdatePushCredentials:credentials forType:(NSString *)type];
}

- (void)pushRegistry:(PKPushRegistry *)registry didInvalidatePushTokenForType:(PKPushType)type
{
}

- (void)pushRegistry:(PKPushRegistry *)registry
    didReceiveIncomingPushWithPayload:(PKPushPayload *)payload
                              forType:(PKPushType)type
                withCompletionHandler:(void (^)(void))completion
{
  NSDictionary *data = payload.dictionaryPayload;
  NSString *uuid = [data[@"uuid"] isKindOfClass:[NSString class]] ? [data[@"uuid"] lowercaseString] : nil;
  if (uuid == nil || [[NSUUID alloc] initWithUUIDString:uuid] == nil) {
    uuid = [[[NSUUID UUID] UUIDString] lowercaseString];
  }
  NSString *callerId = [data[@"callerId"] isKindOfClass:[NSString class]] ? data[@"callerId"] : @"";
  NSString *callerName = [data[@"callerName"] isKindOfClass:[NSString class]] ? data[@"callerName"] : callerId;
  BOOL hasVideo = [data[@"callType"] isKindOfClass:[NSString class]] && [data[@"callType"] isEqualToString:@"video"];

  NSMutableDictionary *forJs = [data mutableCopy];
  forJs[@"uuid"] = uuid;

  // Hand the payload to JavaScript (queued until JS listens), then report the call to CallKit right away.
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
  [RNCallKeep reportNewIncomingCall:uuid
                             handle:callerId
                         handleType:@"generic"
                           hasVideo:hasVideo
                localizedCallerName:callerName
                    supportsHolding:NO
                       supportsDTMF:NO
                   supportsGrouping:NO
                 supportsUngrouping:NO
                        fromPushKit:YES
                            payload:forJs
              withCompletionHandler:completion];
}

@end
`;
}

/** Writes VoipPushHandler.m next to AppDelegate.swift and adds it to the app target. */
export async function configureIosVoipPushHandler(projectDir: string, appName: string): Promise<void> {
  const iosDir = path.join(projectDir, 'ios', appName);
  if (!(await fs.pathExists(iosDir))) return;
  await fs.writeFile(path.join(iosDir, VOIP_PUSH_HANDLER_FILE), getVoipPushHandlerSource(), 'utf8');

  const pbxPath = path.join(projectDir, 'ios', `${appName}.xcodeproj`, 'project.pbxproj');
  if (!(await fs.pathExists(pbxPath))) return;
  const project = xcode.project(pbxPath);
  project.parseSync();
  const groupKey = project.findPBXGroupKey({ name: appName }) || project.findPBXGroupKey({ path: appName });
  const filePath = `${appName}/${VOIP_PUSH_HANDLER_FILE}`;
  if (!groupKey || project.hasFile(filePath)) return;
  project.addSourceFile(filePath, { target: project.getFirstTarget().uuid }, groupKey);
  await fs.writeFile(pbxPath, project.writeSync(), 'utf8');
}

/**
 * Podfile: react-native-agora imports `"RCTBridge.h"` without the `React/` prefix. With the
 * prebuilt React core (React Native's default) that header only exists inside
 * React.framework, so it is added to that one pod's header search paths. Without the
 * prebuilt core the path doesn't exist and is ignored.
 */
export async function configureIosCallingPodfile(projectDir: string, appName: string): Promise<void> {
  const { podfile } = iosPaths(projectDir, appName);
  await edit(podfile, source =>
    applyPatches(
      source,
      [
        {
          id: 'agora-react-headers',
          anchor: /react_native_post_install\([\s\S]*?\n\s*\)/m,
          position: 'after',
          comment: '#',
          content: [
            "agora = installer.pods_project.targets.find { |t| t.name == 'react-native-agora' }",
            'agora&.build_configurations&.each do |config|',
            "  config.build_settings['HEADER_SEARCH_PATHS'] = ['$(inherited)', '\"$(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates/React-Core-prebuilt/React.framework/Headers\"']",
            'end',
          ].join('\n'),
        },
      ],
      'ios/Podfile',
    ),
  );
}

/**
 * Podfile: react-native-permissions – add Microphone permission handler.
 * Camera is added by configureIosCalling separately if video is enabled.
 * The actual setup_permissions call is in ios.ts:configurePodfile.
 */
export function getCallingPodfilePermissions(hasVideo: boolean): string[] {
  const perms = ['Microphone'];
  if (hasVideo) perms.push('Camera');
  return perms;
}
