import { GeneratorError } from './errors.js';

/**
 * Deterministic, idempotent edits of native files generated by the React Native CLI.
 *
 * Each patch is identified by a marker comment. If the marker is present the patch is
 * skipped; if the anchor it relies on is missing we FAIL instead of guessing, because the
 * React Native template changed and the generator must be updated.
 */
export interface Patch {
  /** Unique id, written into the file as a marker comment. */
  id: string;
  /** Where to insert. */
  anchor: RegExp;
  position: 'before' | 'after';
  /** Inserted text (without the marker; the marker line is added automatically). */
  content: string;
  /** Comment syntax of the file. */
  comment: '//' | '#' | 'xml';
}

function markerFor(patch: Patch): string {
  const text = `rn-architecture-generator: ${patch.id}`;
  return patch.comment === 'xml' ? `<!-- ${text} -->` : `${patch.comment} ${text}`;
}

export function hasPatch(source: string, patch: Pick<Patch, 'id'>): boolean {
  return source.includes(`rn-architecture-generator: ${patch.id}`);
}

export function applyPatch(source: string, patch: Patch, fileLabel: string): string {
  if (hasPatch(source, patch)) {
    return source;
  }
  const match = patch.anchor.exec(source);
  if (!match || match.index === undefined) {
    throw new GeneratorError(`Could not configure ${fileLabel} (${patch.id}).`, {
      reason: `Expected to find ${patch.anchor} – the React Native template may have changed.`,
      tryHints: ['Please report this issue; the generated project was rolled back.'],
    });
  }
  // Insert on whole lines, keeping the indentation of the anchor line.
  const lineStart = source.lastIndexOf('\n', match.index) + 1;
  const indent = /^[ \t]*/.exec(source.slice(lineStart))?.[0] ?? '';
  const block = [markerFor(patch), ...patch.content.replace(/\n$/, '').split('\n')]
    .map(line => (line ? indent + line : line))
    .join('\n');

  if (patch.position === 'before') {
    return `${source.slice(0, lineStart)}${block}\n${source.slice(lineStart)}`;
  }
  const endOfMatch = match.index + match[0].length;
  const lineEnd = source.indexOf('\n', endOfMatch);
  const insertAt = lineEnd === -1 ? source.length : lineEnd + 1;
  const prefix = lineEnd === -1 ? `${source}\n` : source.slice(0, insertAt);
  return `${prefix}${block}\n${source.slice(insertAt)}`;
}

export function applyPatches(source: string, patches: Patch[], fileLabel: string): string {
  return patches.reduce((current, patch) => applyPatch(current, patch, fileLabel), source);
}

/** Appends a block at the end of a file (idempotent). */
export function appendBlock(source: string, patch: Omit<Patch, 'anchor' | 'position'>): string {
  if (hasPatch(source, patch)) {
    return source;
  }
  const trimmed = source.replace(/\s*$/, '');
  return `${trimmed}\n\n${markerFor(patch as Patch)}\n${patch.content.replace(/\n$/, '')}\n`;
}
