import type { ArchitectureDefinition } from '../../core/types.js';
import { BASE_GROUPS, DEFAULT_BARRELS } from '../base.js';

export const redux: ArchitectureDefinition = {
  id: 'redux',
  name: 'Redux / State Management Architecture',
  summary: 'A single Redux Toolkit store drives the UI through actions, reducers, thunks and selectors.',
  forcedStateManagement: 'redux',
  groups: {
    ...BASE_GROUPS,
    components: 'src/ui/components',
    screens: 'src/ui/screens',
    navigation: 'src/ui/navigation',
    theme: 'src/ui/theme',
  },
  files: {
    'auth.types': { path: 'src/store/types/auth.ts' },
    'auth.schema': { path: 'src/ui/validation/loginSchema.ts' },
    'auth.service': { path: 'src/services/auth/authService.ts' },
    'auth.form': { path: 'src/ui/components/LoginForm/LoginForm.tsx' },
    'auth.logic': { path: 'src/ui/hooks/useLogin.ts', template: 'architectures/redux/useLogin.ts' },
  },
  extraFiles: [
    {
      id: 'store.authThunks',
      group: 'root',
      file: 'src/store/thunks/authThunks.ts',
      template: 'architectures/redux/authThunks.ts',
    },
  ],
  barrels: DEFAULT_BARRELS,
  docs: {
    concepts: [
      { title: 'UI', body: '`src/ui` – screens and components. They read state with selectors (`useAppSelector`) and dispatch actions (`useAppDispatch`).' },
      { title: 'Action', body: 'Plain actions are generated by slices (`authSlice.actions`). Async work is modelled as thunks in `src/store/thunks` (e.g. `loginThunk`).' },
      { title: 'Reducer', body: '`src/store/slices` – each slice owns one piece of state and the reducers that change it. Combined in `rootReducer.ts`.' },
      { title: 'Store', body: '`src/store/index.ts` configures the Redux Toolkit store and exports `RootState` / `AppDispatch` types.' },
      { title: 'Selector', body: '`src/store/selectors` – the only way UI code reads state, so the state shape can change without touching screens.' },
    ],
    rules: {
      uiComponents: '`src/ui/components`.',
      businessLogic: 'Thunks (`src/store/thunks`) orchestrate async flows; reducers stay pure.',
      apiCalls: 'Thunks call services (`src/services/**`) which use `src/services/api/apiClient.ts`.',
      state: '`src/store` – slices, selectors and thunks. Components never reach into `state.x.y` directly.',
      navigation: '`src/ui/navigation`.',
    },
  },
};
