import { Schema, model, type InferSchemaType, type Types } from 'mongoose';
import { DeviceType } from '{{IMPORT:domain.device}}';

/** One app install of a user (a user can have several devices). */
const deviceSchema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    // Generated by the app once per install.
    deviceId: { type: String, required: true, unique: true, maxlength: 128 },
    // FCM registration token (null until the app has one) – unique when set, see the index below.
    fcmToken: { type: String, default: null, maxlength: 512 },
    deviceType: { type: String, required: true, enum: Object.values(DeviceType) },
    deviceModel: { type: String, default: null, maxlength: 120 },
    osVersion: { type: String, default: null, maxlength: 32 },
    appVersion: { type: String, default: null, maxlength: 32 },
    lastActiveAt: { type: Date, required: true, default: Date.now },
  },
  { timestamps: true, collection: 'devices' },
);
deviceSchema.index({ fcmToken: 1 }, { unique: true, partialFilterExpression: { fcmToken: { $type: 'string' } } });

export type DeviceDocument = InferSchemaType<typeof deviceSchema> & { _id: Types.ObjectId; userId: Types.ObjectId; createdAt: Date; updatedAt: Date };
export const DeviceModel = model('Device', deviceSchema);
