import { z } from 'zod';
import { emptySchema } from '{{IMPORT:ex.schemas}}';
import { route, WithMeta, type RouteGroup } from '{{IMPORT:ex.route}}';
import {
  chatMessageSchema,
  conversationParams,
  conversationSchema,
  listMessagesQuery,
  messageParams,
  sendMessageSchema,
  startConversationSchema,
  uploadedMediaSchema,
} from '{{IMPORT:ex.chat.schemas}}';

/** `/chat` – the endpoints of the app's chatEndpoints.ts. Live events: see the Socket.IO server. */
export const chatRoutes: RouteGroup = {
  prefix: '/chat',
  tag: 'Chat',
  routes: [
    route({
      method: 'get',
      path: '/conversations',
      summary: 'Your conversations, newest activity first',
      message: 'Conversations',
      auth: true,
      response: z.array(conversationSchema),
      errors: [401],
      handler: ({ user }, { chat }) => chat.listConversations(user.id),
    }),
    route({
      method: 'post',
      path: '/conversations',
      summary: 'Open a direct chat (reuses the existing one) or create a group',
      message: 'Conversation',
      auth: true,
      body: startConversationSchema,
      response: conversationSchema,
      errors: [400, 401, 404, 422],
      handler: ({ user, body }, { chat }) => chat.startConversation(user.id, body),
    }),
    route({
      method: 'get',
      path: '/conversations/:conversationId',
      summary: 'One conversation',
      message: 'Conversation',
      auth: true,
      params: conversationParams,
      response: conversationSchema,
      errors: [401, 404],
      handler: ({ user, params }, { chat }) => chat.getConversation(user.id, params.conversationId),
    }),
    route({
      method: 'delete',
      path: '/conversations/:conversationId',
      summary: 'Delete a chat for you (direct) or leave a group',
      message: 'Conversation deleted',
      auth: true,
      params: conversationParams,
      response: emptySchema,
      errors: [401, 404],
      handler: ({ user, params }, { chat }) => chat.deleteConversation(user.id, params.conversationId),
    }),
    route({
      method: 'get',
      path: '/conversations/:conversationId/messages',
      summary: 'Messages, oldest → newest (`before` loads older pages; meta.hasMore)',
      message: 'Messages',
      auth: true,
      params: conversationParams,
      query: listMessagesQuery,
      response: z.array(chatMessageSchema),
      errors: [401, 404, 422],
      async handler({ user, params, query }, { chat }) {
        const { items, hasMore } = await chat.listMessages(user.id, params.conversationId, query);
        return new WithMeta(items, { hasMore });
      },
    }),
    route({
      method: 'post',
      path: '/conversations/:conversationId/messages',
      summary: 'Send a message (members get `chat:receive_message`)',
      message: 'Message sent',
      status: 201,
      auth: true,
      params: conversationParams,
      body: sendMessageSchema,
      response: chatMessageSchema,
      errors: [400, 401, 404, 422],
      handler: ({ user, params, body }, { chat }) => chat.sendMessage(user.id, params.conversationId, body),
    }),
    route({
      method: 'post',
      path: '/conversations/:conversationId/read',
      summary: 'Mark the conversation as read (others get `chat:message_read`)',
      message: 'Marked as read',
      auth: true,
      params: conversationParams,
      response: emptySchema,
      errors: [401, 404],
      handler: ({ user, params }, { chat }) => chat.markRead(user.id, params.conversationId),
    }),
    route({
      method: 'delete',
      path: '/conversations/:conversationId/messages/:messageId',
      summary: 'Delete one of your messages for everyone',
      message: 'Message deleted',
      auth: true,
      params: messageParams,
      response: emptySchema,
      errors: [401, 403, 404],
      handler: ({ user, params }, { chat }) => chat.deleteMessage(user.id, params.conversationId, params.messageId),
    }),
    route({
      method: 'post',
      path: '/upload',
      summary: 'Upload a photo, video, audio or document (multipart field `file`) – then send its url',
      message: 'File uploaded',
      status: 201,
      auth: true,
      upload: 'file',
      response: uploadedMediaSchema,
      errors: [400, 401, 413, 422],
      handler: ({ user, file }, { chat }) => chat.uploadMedia(user.id, file),
    }),
    route({
      method: 'post',
      path: '/upload-voice',
      summary: 'Upload a voice note (multipart field `file`, audio only)',
      message: 'Voice note uploaded',
      status: 201,
      auth: true,
      upload: 'file',
      response: uploadedMediaSchema,
      errors: [400, 401, 413, 422],
      handler: ({ user, file }, { chat }) => chat.uploadMedia(user.id, file, true),
    }),
  ],
};
