import { z } from 'zod';
import { DEVICE_PLATFORMS } from '{{IMPORT:domain.device}}';

export const registerDeviceSchema = z
  .object({
    deviceId: z.string().trim().min(8).max(128).meta({ description: 'Generated by the app once per install' }),
    token: z.string().min(10).max(512).nullable().optional().meta({ description: 'FCM registration token (null when the app has none)' }),
    platform: z.enum(DEVICE_PLATFORMS),
    deviceName: z.string().trim().max(120).nullable().optional().meta({ description: 'e.g. "Pixel 8"' }),
    osVersion: z.string().trim().max(32).nullable().optional(),
    appVersion: z.string().trim().max(32).nullable().optional(),
  })
  .meta({ id: 'RegisterDeviceRequest' });

export const deviceParams = z.object({ deviceId: z.string().min(1).max(128) });

// ── responses (used by the OpenAPI document) ──────────────────────────────────

export const deviceSchema = z
  .object({
    deviceId: z.string(),
    platform: z.enum(DEVICE_PLATFORMS),
    deviceName: z.string().nullable(),
    osVersion: z.string().nullable(),
    appVersion: z.string().nullable(),
    pushEnabled: z.boolean(),
    lastActiveAt: z.iso.datetime(),
    createdAt: z.iso.datetime(),
  })
  .meta({ id: 'Device' });
