import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn, UpdateDateColumn, Index } from 'typeorm';
import { TIMESTAMP, UuidColumn } from '{{IMPORT:typeorm.columns}}';
import { DeviceType } from '{{IMPORT:domain.device}}';
import { UserOrmEntity } from '{{IMPORT:typeorm.user}}';

/** One app install of a user (a user can have several devices). */
@Entity({ name: 'devices' })
export class DeviceOrmEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Index()
  @UuidColumn({ name: 'user_id' })
  userId: string;

  @ManyToOne(() => UserOrmEntity, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user?: UserOrmEntity;

  /** Generated by the app once per install. */
  @Column({ name: 'device_id', type: 'varchar', length: 128, unique: true })
  deviceId: string;

  /** FCM registration token (null until the app has one). */
  @Column({ name: 'fcm_token', type: 'varchar', length: 512, unique: true, nullable: true })
  fcmToken: string | null;

  /** iOS VoIP push token for incoming calls (null on Android or until registered). */
  @Column({ name: 'voip_token', type: 'varchar', length: 512, nullable: true })
  voipToken: string | null;

  @Column({ name: 'device_type', type: 'enum', enum: DeviceType, enumName: 'device_type' })
  deviceType: DeviceType;

  @Column({ name: 'device_model', type: 'varchar', length: 120, nullable: true })
  deviceModel: string | null;

  @Column({ name: 'os_version', type: 'varchar', length: 32, nullable: true })
  osVersion: string | null;

  @Column({ name: 'app_version', type: 'varchar', length: 32, nullable: true })
  appVersion: string | null;

  @Column({ name: 'last_active_at', type: TIMESTAMP, default: () => 'CURRENT_TIMESTAMP' })
  lastActiveAt: Date;

  @CreateDateColumn({ name: 'created_at', type: TIMESTAMP })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: TIMESTAMP })
  updatedAt: Date;
}
