import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn, UpdateDateColumn, Index } from 'typeorm';
import { TIMESTAMP, UuidColumn } from '{{IMPORT:typeorm.columns}}';
import { UserOrmEntity } from '{{IMPORT:typeorm.user}}';

/** One app install of a user (a user can have several devices). */
@Entity({ name: 'devices' })
export class DeviceOrmEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Index()
  @UuidColumn({ name: 'user_id' })
  userId: string;

  @ManyToOne(() => UserOrmEntity, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user?: UserOrmEntity;

  /** Generated by the app once per install. */
  @Column({ name: 'device_id', type: 'varchar', length: 128, unique: true })
  deviceId: string;

  /** FCM registration token (null until the app has one). */
  @Column({ type: 'varchar', length: 512, unique: true, nullable: true })
  token: string | null;

  @Column({ type: 'varchar', length: 16 })
  platform: string;

  @Column({ name: 'device_name', type: 'varchar', length: 120, nullable: true })
  deviceName: string | null;

  @Column({ name: 'os_version', type: 'varchar', length: 32, nullable: true })
  osVersion: string | null;

  @Column({ name: 'app_version', type: 'varchar', length: 32, nullable: true })
  appVersion: string | null;

  @Column({ name: 'last_active_at', type: TIMESTAMP, default: () => 'CURRENT_TIMESTAMP' })
  lastActiveAt: Date;

  @CreateDateColumn({ name: 'created_at', type: TIMESTAMP })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: TIMESTAMP })
  updatedAt: Date;
}
